backend:
  name: git-gateway
  branch: main
  repo: alianza/portfolio-lea

local_backend: true
site_url: https://leashamaa.nl
display_url: https://leashamaa.nl
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow
#logo_url: https://pensive-mclean-91ddb5.netlify.app/images/logo.webp

collections:
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "config"
        label: "Site Config"
        file: "content/config.json"
        description: "General site settings"
        fields:
          - { label: "Site title", name: "site_title", widget: "string" }
          - { label: "Site description", name: "site_description", widget: "string" }
          - label: "Categories"
            name: "categories"
            label_singular: "Category"
            widget: "list"
            summary: "{{fields.name}}"
            fields:
              - { label: "Category name", name: "name", widget: "string" }
          - label: "Online accounts"
            name: "accounts"
            label_singular: "Online account"
            widget: "list"
            summary: "{{fields.name}}"
            fields:
              - { label: "Social media name", name: "name", widget: "string" }
              - { label: "Url", name: "url", widget: "string" }
              - { label: "Icon", name: "icon", widget: "image" }

  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'About'
        name: 'about'
        file: 'content/pages/about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string', required: true }
          - { label: 'Publish Date', name: 'date', widget: 'datetime', required: true, format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
          - { label: 'Body', name: 'body', widget: 'markdown', required: true }

  - label: 'Posts'
    name: 'post'
    label_singular: 'Post'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', required: true, format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image', required: true }
      - { label: "Category", name: "category", widget: "relation", collection: "config", file: "config",
          search_fields: [ "categories.*.name" ],
          display_fields: [ "categories.*.name" ],
          value_field: "categories.*.name"
      }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
