backend:
  name: git-gateway
  branch: main
  repo: alianza/portfolio-lea

local_backend: true
site_url: https://leashamaa.nl
display_url: https://leashamaa.nl
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow
#logo_url: https://pensive-mclean-91ddb5.netlify.app/images/logo.webp

collections:
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "config"
        label: "Site Config"
        file: "content/config.json"
        description: "General site settings"
        fields:
          - { label: "Site heading", name: "site_heading", widget: "string" }
          - { label: "Site title", name: "site_title", widget: "string" }
          - { label: "Site description", name: "site_description", widget: "text" }
          - { label: "Medium username", name: "username_medium", widget: "string" }
          - label: "Categories"
            name: "categories"
            label_singular: "Category"
            widget: "list"
            summary: "{{fields.name}}"
            fields:
              - { label: "Category name", name: "name", widget: "string" }
              - { label: "Category color", name: "color", widget: "color", required: false }
              - { label: "Text color", name: "textColor", widget: "select", options: [ "auto", "light", "dark" ], default: ["auto"] }
          - label: "Online accounts"
            name: "accounts"
            label_singular: "Online account"
            widget: "list"
            summary: "{{fields.name}}"
            fields:
              - { label: "Social media name", name: "name", widget: "string" }
              - { label: "Url", name: "url", widget: "string" }
              - { label: "Icon", name: "icon", widget: "image" }

  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'content/pages/home.md'
        editor:
          preview: false
        fields:
          - { label: 'Portfolio title', name: 'portfolioTitle', widget: 'string' }
          - { label: 'Portfolio link label', name: 'portfolioLabel', widget: 'string' }
          - { label: 'Blog title', name: 'blogTitle', widget: 'string' }
          - { label: 'Blog link label', name: 'blogLabel', widget: 'string' }
          - { label: 'Articles title', name: 'articlesTitle', widget: 'string' }
          - { label: 'Articles link label', name: 'articlesLabel', widget: 'string' }
          - label: "Quotes"
            name: "quotes"
            label_singular: "Quote"
            widget: "list"
            summary: "{{fields.quote}} - {{fields.author}}"
            fields:
              - { label: "Quote", name: "quote", widget: "string" }
              - { label: "Author", name: "author", widget: "string" }
      - label: 'About'
        name: 'about'
        file: 'content/pages/about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Categories'
        name: 'categories'
        file: 'content/pages/categories.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown', required: false }
      - label: 'Portfolio'
        name: 'portfolio'
        file: 'content/pages/portfolio.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Articles'
        name: 'articles'
        file: 'content/pages/articles.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - label: "Read more link"
            name: "readMoreLink"
            widget: "object"
            summary: '{{fields.label}}'
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
      - label: 'Blog'
        name: 'blog'
        file: 'content/pages/blog.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Contact'
        name: 'contact'
        file: 'content/pages/contact.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }

  - label: 'Posts'
    name: 'post'
    label_singular: 'Post'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: "DD-MM-YYYY", date_format: "DD-MM-YYYY", time_format: false }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { label: "Category", name: "category", widget: "relation",
          collection: "config", file: "config",
          search_fields: [ "categories.*.name" ], display_fields: [ "categories.*.name" ], value_field: "categories.*.name" }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - label: 'Experiences'
    name: 'experience'
    label_singular: 'Post'
    folder: 'content/experiences'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Start Date', name: 'startDate', widget: 'datetime', format: "DD-MM-YYYY", date_format: "DD-MM-YYYY", time_format: false }
      - { label: 'End Date', name: 'endDate', widget: 'datetime', format: "DD-MM-YYYY", date_format: "DD-MM-YYYY", time_format: false, required: false, hint: "Leave empty if still working (present)" }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
